### ISSUE TITLE
Broken after recent Obsidian and/or Zoom plugin update?

### ISSUE THREAD

**Issue by cansar** [nothingislost/obsidian-cm6-zoom#1]
Hi,

I've been using the plugin without any issues since the early Alpha and it's worked perfectly. After updating Obsidian today (and possibly the plugin - not sure if BRAT updated it) I'm getting a "In order to zoom, you must first enable "Fold heading" and "Fold indent" under Settings -> Editor" error despite having fold on. I restarted a few times and toggled the settings on/off to see if that helped.

Let me know if I can provide any other options?

**Comment by nothingislost** [comment]
Hmm, you definitely have both fold options enabled?

![image](https://user-images.githubusercontent.com/89109712/145695888-38ed5728-b0cb-40c3-815d-c89e40b68317.png)

Also, please make sure you're on version 0.1.0 of the plugin.

![image](https://user-images.githubusercontent.com/89109712/145695917-70feca52-afae-4dca-b897-7c821d50cc25.png)

**Comment by cansar** [comment]
UGH, it was the version number. Thank you!

I didn't realize BRAT plugins need a separate update command and aren't updated when updating community plugins. My bad
